# app/config/security.yml
security:
    providers:
      our_db_provider:
        entity:
          class: AcmeStoreBundle:User
          property: idUsuario

    firewalls:
      default:
        anonymous: ~
        http_basic: ~
        form_login:
          login_path: /login
          check_path: /login_check
          username_parameter: _username
          password_parameter: _password
        logout:
          path: /logout
          target: /login

      dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
      main:
            anonymous: ~
            # activate different ways to authenticate
    encoders:
        AcmeStoreBundle\Entity\User:
          algorithm:  bcrypt
          cost: 12